from .alpha_chroma_key import NODE_CLASS_MAPPINGS as ALPHA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_DISPLAY_MAPPINGS
from .border_region_mask import NODE_CLASS_MAPPINGS as BORDER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BORDER_DISPLAY_MAPPINGS
from .mask_erode import NODE_CLASS_MAPPINGS as ERODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ERODE_DISPLAY_MAPPINGS
from .mask_dilate import NODE_CLASS_MAPPINGS as DILATE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DILATE_DISPLAY_MAPPINGS
from .mask_blur import NODE_CLASS_MAPPINGS as BLUR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BLUR_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {**ALPHA_MAPPINGS, **BORDER_MAPPINGS, **ERODE_MAPPINGS, **DILATE_MAPPINGS, **BLUR_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**ALPHA_DISPLAY_MAPPINGS, **BORDER_DISPLAY_MAPPINGS, **ERODE_DISPLAY_MAPPINGS, **DILATE_DISPLAY_MAPPINGS, **BLUR_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

