from .alpha_chroma_key import NODE_CLASS_MAPPINGS as ALPHA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_DISPLAY_MAPPINGS
from .border_region_mask import NODE_CLASS_MAPPINGS as BORDER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BORDER_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {**ALPHA_MAPPINGS, **BORDER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**ALPHA_DISPLAY_MAPPINGS, **BORDER_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

