from .alpha_chroma_key import NODE_CLASS_MAPPINGS as ALPHA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_DISPLAY_MAPPINGS
from .alpha_chroma_key_enhanced import NODE_CLASS_MAPPINGS as ALPHA_ENHANCED_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_ENHANCED_DISPLAY_MAPPINGS
from .border_region_mask import NODE_CLASS_MAPPINGS as BORDER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BORDER_DISPLAY_MAPPINGS
from .alpha_background import NODE_CLASS_MAPPINGS as ALPHA_BACKGROUND_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_BACKGROUND_DISPLAY_MAPPINGS
from .mask_erode import NODE_CLASS_MAPPINGS as ERODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ERODE_DISPLAY_MAPPINGS
from .mask_dilate import NODE_CLASS_MAPPINGS as DILATE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DILATE_DISPLAY_MAPPINGS
from .mask_blur import NODE_CLASS_MAPPINGS as BLUR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BLUR_DISPLAY_MAPPINGS
from .pad_image import NODE_CLASS_MAPPINGS as PAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PAD_DISPLAY_MAPPINGS
from .stroke import NODE_CLASS_MAPPINGS as OUTLINE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OUTLINE_DISPLAY_MAPPINGS
from .alpha_edge_erode import NODE_CLASS_MAPPINGS as ALPHA_EDGE_ERODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_EDGE_ERODE_DISPLAY_MAPPINGS
from .alpha_edge_dilate import NODE_CLASS_MAPPINGS as ALPHA_EDGE_DILATE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_EDGE_DILATE_DISPLAY_MAPPINGS
from .alpha_stroke import NODE_CLASS_MAPPINGS as ALPHA_STROKE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_STROKE_DISPLAY_MAPPINGS
from .add_background import NODE_CLASS_MAPPINGS as ADD_BACKGROUND_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ADD_BACKGROUND_DISPLAY_MAPPINGS
from .load_image_alpha import NODE_CLASS_MAPPINGS as LOAD_IMAGE_ALPHA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_IMAGE_ALPHA_DISPLAY_MAPPINGS
from .alpha_remove_small_regions import NODE_CLASS_MAPPINGS as ALPHA_REMOVE_SMALL_REGIONS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_REMOVE_SMALL_REGIONS_DISPLAY_MAPPINGS
from .alpha_remove_thin_lines import NODE_CLASS_MAPPINGS as ALPHA_REMOVE_THIN_LINES_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALPHA_REMOVE_THIN_LINES_DISPLAY_MAPPINGS
from .resize_and_pad_alpha import NODE_CLASS_MAPPINGS as RESIZE_AND_PAD_ALPHA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESIZE_AND_PAD_ALPHA_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {**ALPHA_MAPPINGS, **ALPHA_ENHANCED_MAPPINGS, **BORDER_MAPPINGS, **ALPHA_BACKGROUND_MAPPINGS, **ERODE_MAPPINGS, **DILATE_MAPPINGS, **BLUR_MAPPINGS, **PAD_MAPPINGS, **OUTLINE_MAPPINGS, **ALPHA_EDGE_ERODE_MAPPINGS, **ALPHA_EDGE_DILATE_MAPPINGS, **ALPHA_STROKE_MAPPINGS, **ADD_BACKGROUND_MAPPINGS, **LOAD_IMAGE_ALPHA_MAPPINGS, **ALPHA_REMOVE_SMALL_REGIONS_MAPPINGS, **ALPHA_REMOVE_THIN_LINES_MAPPINGS, **RESIZE_AND_PAD_ALPHA_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**ALPHA_DISPLAY_MAPPINGS, **ALPHA_ENHANCED_DISPLAY_MAPPINGS, **BORDER_DISPLAY_MAPPINGS, **ALPHA_BACKGROUND_DISPLAY_MAPPINGS, **ERODE_DISPLAY_MAPPINGS, **DILATE_DISPLAY_MAPPINGS, **BLUR_DISPLAY_MAPPINGS, **PAD_DISPLAY_MAPPINGS, **OUTLINE_DISPLAY_MAPPINGS, **ALPHA_EDGE_ERODE_DISPLAY_MAPPINGS, **ALPHA_EDGE_DILATE_DISPLAY_MAPPINGS, **ALPHA_STROKE_DISPLAY_MAPPINGS, **ADD_BACKGROUND_DISPLAY_MAPPINGS, **LOAD_IMAGE_ALPHA_DISPLAY_MAPPINGS, **ALPHA_REMOVE_SMALL_REGIONS_DISPLAY_MAPPINGS, **ALPHA_REMOVE_THIN_LINES_DISPLAY_MAPPINGS, **RESIZE_AND_PAD_ALPHA_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

